### PR TITLE
Add multimedia folders

### PR DESCRIPTION
**Pull request by kay0u**
## Problem
- *[Airsonic unable to read /home/yunohost.multimedia/share/Music](https://github.com/YunoHost-Apps/airsonic_ynh/issues/3)*

## Solution
- *Add multimedia*
- *10.4.1*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
- [ ] **Code review**
- [ ] **Approval (LGTM)**  
*Code review and approval have to be from a member of @YunoHost/apps group*
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/airsonic_ynh%20(Kay0u)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by kay0u** [comment]
BTW, what do you think about asking for the status of "high quality package" for airsonic?

**Comment by kay0u** [comment]
Bump

**Comment by kay0u** [comment]
Yolomerging

**Comment by Gofannon** [comment]
> 
> 
> BTW, what do you think about asking for the status of "high quality package" for airsonic?

Why not. I lack time to maintain it correctly and quickly though.

The package also gets killed sometimes because of lack of ram (oom-killer does its job)

**Comment by kay0u** [comment]
I don't understand why, because we limit the memory usage with -Xmx700m...

**Comment by Gofannon** [comment]
> I don't understand why, because we limit the memory usage with -Xmx700m...

Because I have too much services on my server for its 2 Gb of RAM
One day, it could be interesting to "tune" this value with a lower or bigger number depending of the usage of the service

**Pull request merged**
