### PR TITLE
10.6.0

### PR DESCRIPTION
**Pull request by Aeris1One**
## Problem
- *Actual version is outdated*

## Solution
- *Update the app*

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
- [ ] **Code review**
- [ ] **Approval (LGTM)**  
*Code review and approval have to be from a member of @YunoHost/apps group*
- **CI succeeded** : 
[Build Status](https://ci-apps-dev.yunohost.org/jenkins/job/airsonic_ynh%20PR28/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by Aeris1One** [comment]
Next time i'll first check if there's no other PR :/

**Comment by Gofannon** [comment]
> Next time i'll first check if there's no other PR :/

Thank you for your PR. At least you can compare with mine about what you can improve for the next one :)
I did that mistake once... Always check if there is one PR ongoing! Also, EACH time that you create a new branch to work on something, create a draft PR to show people that someone is working on it.

Are you interested to become a maintainer of this app? I don't really use it daily and I use the web app mainly, not really from a smartphone as I saw on the forum. As you seem interested to propose a PR so quickly after the release of the upstream app :)

There is more than code too. There is the communication on the forum about new realeases to show people that the package is "healthy" (testing or master)

**Comment by Aeris1One** [comment]
Do you stop maintaining Ampache? 
At the moment I am not available to make big changes, this little PR was simple and quick to make so that's ok.
I would be happy to maintain Ampache since I use it very often. 
Unfortunately at the moment I don't have time.
Furthermore, I'm also maintaining two others packages, the high-quality Hextris (which does not needs any effort to maintain) and Pterodactyl, and the second one needs a full recode to work with new YunoHost and Pterodactyl version.
So, I can't help maintaining ampache for now, maybe in a few weeks I will be able to help you.

**Comment by kay0u** [comment]
/Ampache/Airsonic/ :wink:

**Comment by Aeris1One** [comment]
Yup, sry, edited 😅
I'm also trying to debug Ampach_ynh which is broken so I can confuse.

**Comment by Gofannon** [comment]
> Do you stop maintaining Airsonic?

Yes. Just for my use case mainly. I can't spend too much time on it.

Thanks for your answer and good luck with Ampache !

**Pull request closed without merging**
